backend:
  name: github
  repo: smthmb/blog
  branch: main
  base_url: https://cms-auth.matikusm.workers.dev

media_folder: "assets/images/uploads"
public_folder: "assets/images/uploads"

collections:
  - name: "blog"
    label: "blog posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "title", name: "title", widget: "string" }
      - { label: "publish date", name: "date", widget: "datetime" }
      - { label: "body", name: "body", widget: "markdown" }
