backend:
  name: github
  repo: smthmb/blog
  branch: main
  base_url: https://cms-auth.matikusm.workers.dev
  auth_endpoint: auth

site_url: https://smthmatt.pl/blog/admin
display_url: https://smthmatt.pl/blog/admin

media_folder: "assets/images/uploads"
public_folder: "assets/images/uploads"

collections:
  - name: "blog"
    label: "blog posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "title", name: "title", widget: "string" }
      - { label: "publish date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm", date_format: "YYYY-MM-DD", time_format: "HH:mm" }
      - { label: "body", name: "body", widget: "markdown" }
